import { Container } from "@/components/container";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white pt-32 pb-24">
      <Container className="max-w-4xl">
        <p className="text-xs font-bold text-indigo-600 uppercase tracking-[0.2em] mb-4">
          MIFA Dynamics
        </p>
        <h1 className="text-3xl font-extrabold tracking-tight text-zinc-900 md:text-6xl mb-8 md:mb-12">
          Terms of Engagement
        </h1>

        <div className="prose prose-zinc prose-base md:prose-lg max-w-none font-medium text-zinc-600 leading-relaxed space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-zinc-900 mb-4">
              1. Scope of Service
            </h2>
            <p>
              By accessing the MIFA Dynamics platform, you engage with our
              procedural engine for technical and educational purposes. This is
              an expert-level tool designed for the synthesis of complex
              conceptual simulations through generative AI pipelines.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-zinc-900 mb-4">
              2. Intellectual Integrity
            </h2>
            <p>
              Users retain ownership of their original conceptual queries.
              However, the procedural logic and engine results generated by MIFA
              Dynamics are provided under a technical usage license intended for
              education and research validation. Unauthorised commercial
              exploitation of procedural engine outputs is strictly governed by
              our commercial lab agreements.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-zinc-900 mb-4">
              3. Acceptable Technical Use
            </h2>
            <p>
              Engagement with the engine must follow our expert-validated
              security protocols. Reverse engineering procedural generation
              logic or manipulating multi-agent architectures is a direct
              violation of our core terms.
            </p>
          </section>

          <section className="pt-8 border-t border-zinc-100 italic text-zinc-400 text-sm">
            Last updated: February 26, 2026. Terms subject to laboratory review.
          </section>
        </div>
      </Container>
    </main>
  );
}
